dist: trusty
sudo: required
language:
  - rust

script:
  - cargo build --release --verbose
  - cargo test --verbose --features std
  - cargo test --verbose --manifest-path=tests/Cargo.toml --features=pwasm-std/std
