[package]
name = "pwasm-abi"
version = "0.1.0"
authors = ["NikVolf <nikvolf@gmail.com>"]

[profile.release]
panic = "abort"

[dependencies]
tiny-keccak = "*"
rustc-hex = { version = "1.0", optional = true }
bigint = "4"
parity-hash = "1"


[dependencies.byteorder]
version = "1"
default-features = false

[features]
std = ["rustc-hex"]
