[package]
name = "pwasm-abi-derive"
version = "0.1.0"
authors = ["NikVolf <nikvolf@gmail.com>"]

[profile.release]
panic = "abort"

[dependencies]
pwasm-abi = { path = ".." }
quote = "0.3"
syn = { version = "0.11", features = ["full"] }
tiny-keccak = "*"
byteorder = "1"
parity-hash = "1"

[lib]
name = "pwasm_abi_derive"
proc-macro = true